### ISSUE TITLE
404 on GeoIP Download

### ISSUE THREAD

**Issue by makenai** [sapics/geoip-country#1]
Seems like maybe they've changed the URL around?

`Fetching  https://geolite.maxmind.com/download/geoip/database/GeoIPCountryCSV.zip
Retrieving GeoIPCountryCSV.zip ...{path redacted}\node_modules\geoip-country\scripts\updatedb.js:131
                        console.log('ERROR'.red + ': HTTP Request Failed [%d %s]', status, https.STATUS_CODES[status]);`

**Comment by sapics** [comment]
@makenai  Thanks for reporting!
As you noticed, they would change the URL to https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country-CSV.zip
The zip file looks change from the previous one. I will check it and fix this library.

**Comment by sapics** [comment]
I fix updatedb.js by referencing original repository https://github.com/bluesmoon/node-geoip :)
And I have updated the npm to v3.2.0.
Thank you, again!

**Comment by makenai** [comment]
@sapics Thank you! I noticed later that the repo you've forked from switched to that URL, but I wasn't sure of the particulars of the file format and was a little discouraged by the warning on the download page that it was only for geoip2 clients. Sorry, I didn't put together a PR or post more info, I was pretty disorganized yesterday. Thanks for the really fast fix!

**Comment by sapics** [comment]
@makenai  Don't warry about that ;) I am really appreciate your reporting.
I will close this issue, because it would be fixed. If you find any problem on v3.2.0, it would be grateful if you could notice to me.
Thank you for reporting and kind reply!
