### ISSUE TITLE
CLI param for license in update not supported anymore?

### ISSUE THREAD

**Issue by apfelbox** [sapics/geoip-country#14]
Hi,

I just implemented this package and noticed in the update script, that it only tries two env vars for reading the license key:

https://github.com/sapics/geoip-country/blob/master/scripts/updatedb.js#L7

`npm_config_license_key` and `GEOLITE2_LICENSE_KEY`

So it doesn't seem like that the CLI param is still supported?
I tried whether it is automagically mangled into the first env var, but at least for pnpm it isn't.

**Comment by sapics** [comment]
I guess that CLI param `--license_key=XXXXXX` would be still supported.

**Comment by apfelbox** [comment]
Hi @sapics,

I tried that but it doesn't work:
![Screenshot_2023-06-28_13 54 05](https://github.com/sapics/geoip-country/assets/1032411/97f8b7e3-c9cf-4f1f-add2-2f386f071e3b)

The file also never access `process.argv`, so I am not sure how that is supposed to work?
https://github.com/sapics/geoip-country/blob/master/scripts/updatedb.js

Or am I missing something?

**Comment by sapics** [comment]
Thanks for the additional confirmation!
Since npm_config_license_key is valid with the `npm` command, I guess it did not work with the `node` command.
I commited on https://github.com/sapics/geoip-country/commit/6ad342145f5621962b4c354a63b8086082dde90a to fix it to work with the `node` command, and released v4.2.0.

**Comment by sapics** [comment]
I guess that the issue would be fixed in newer version, thus, I close this issue.
Feel free to reopen this issue, when you find problems.
