### ISSUE TITLE
Allow storing the database files in a custom directory

### ISSUE THREAD

**Issue by apfelbox** [sapics/geoip-country#15]
Hi,

it would be great if it would be allowed to configure a separate directory for storing the database files in.
Our hosting has a readonly-filesystem for everything except specific mounts and I would like to avoid having `node_modules` completely mutable.

Is that possible?
I could try to help with the implementation.

**Comment by sapics** [comment]
It looks very good feature!

I create a `custom-dir` branch for this issue. Could you try the branch?
You could use custom dir with environment `GEODATADIR` and `TMPDATADIR`, or CLI parameter `--geodatadir=XXXXXX` and `--tmpdatadir=XXXXXX`.

**Comment by apfelbox** [comment]
The implementation is looking great, I just pushed some small tweaks in https://github.com/sapics/geoip-country/pull/16

**Comment by sapics** [comment]
Thank you for checking and fixing bug! I merge to master branch with your commits!

**Comment by apfelbox** [comment]
Thanks for merging @sapics 🙌 

One thing to note is though, that right now, if you install the package with a custom data dir, you need to first update the dbs, as it won't use the bundled ones by default.
That might be worth documenting.

Do you already have an ETA for the next release in mind?

**Comment by sapics** [comment]
Thank you for noticing!

I added the documentation about Custom Directory in README. https://github.com/sapics/geoip-country#custom-directory-for-database-files
I hope that the sentense `For creating and updating ...` explains your concerns. (I am not good at English.)

Currently, this is automatically updated twice a week, so the next update will be made within 48 hours.
