### ISSUE TITLE
fs.readFileSync is not a function

### ISSUE THREAD

**Issue by marioliu** [sapics/geoip-country#2]
Hi, when I try to do `geoip.lookup(ip)`, I get the error `fs.readFileSync is not a function`. I'm trying to run the code on the client, on a browser. Is there a way to do this? Thanks!

**Comment by sapics** [comment]
Sorry, this is not possible to work on a browser.
And the ip database is about 5MB, it would be bad for client to download. 
ip2c.org looks good for browser!
