### ISSUE TITLE
Colored Output: undefined

### ISSUE THREAD

**Issue by apfelbox** [sapics/geoip-country#20]
Hi,

the scripts and package are working flawlessly, however when I try to update the db, I get a lot of `undefined` in the output.
I guess that's due to the `.green` / `.blue` on strings being undefined.

What do I need to load before for that to work / can this be refactored to use regular functions from `kleur` or similar?

I call the script basically by doing:

```bash
node ./node_modules/geoip-country/scripts/updatedb.js
```

with a bunch of environment variables.

Example output:

```txt
Fetching new databases from MaxMind...
Storing files at undefined
Fetching edition GeoLite2-Country-CSV from https://download.maxmind.com/app/geoip_download
Retrieving GeoLite2-Country-CSV.zip ...undefined
Extracting GeoLite2-Country-CSV.zip ...Processing Lookup Data (may take a moment) ...undefined
Processing Data (may take a moment) ...
Still working (95245) ...
Still working (196729) ...
Still working (297143) ...
Still working (398424) ...undefined
Processing Data (may take a moment) ...
Still working (63705) ...
Still working (128039) ...
Still working (189823) ...
Still working (251464) ...undefined
undefined
```

**Comment by sapics** [comment]
Thank you for reporting the bug!
This bug was created when I dropped `colors` module as https://github.com/sapics/geoip-country/commit/d88d5b6de3f3eb0db55a1617d4e29abedcb9e341, #18.
Now, I remove the `.blue`, `.green`, `.red` from the update script, and update npm package.

**Comment by sapics** [comment]
I close this as fixed. If you find any bugs, feel free to reopen this issue or create new issue.
