### ISSUE TITLE
`updatedb.js` script seems to be unable to handle redirects

### ISSUE THREAD

**Issue by binaryunary** [sapics/geoip-country#24]
Hi,

I'm using `geoip-country@4.2.72` and it seems the included update script is unable to handle redirects when fetching the DB data. 

Here's the console output:
```bash
Fetching new databases from MaxMind...
Storing files at /some/path/node_modules/geoip-country/data
Fetching edition GeoLite2-Country-CSV from https://download.maxmind.com/app/geoip_download
Retrieving GeoLite2-Country-CSV.zip ...ERROR: HTTP Request Failed [302]
```

**Comment by sapics** [comment]
Thank you for reporting the error!

I try to fix the issue in https://github.com/sapics/geoip-country/commit/a8b4194ade842ad12fc7fca16a105d3e10e46ee1.
I update npm version to `geoip-country@4.2.73`. Could you try this?

**Comment by binaryunary** [comment]
@sapics, I just tested with 4.2.73 and it seems fixed. Big thanks!

**Comment by sapics** [comment]
Thank you for quick testing and response!
