### ISSUE TITLE
Ability to run "updatedb" with a GeoIP license key

### ISSUE THREAD

**Issue by valeriansaliou** [sapics/geoip-country#3]
Hello there!

Since recent Maxmind/GeoIP changes regarding database downloads and licensing, it would be great to be able to pass a license key (as an argument or environment variable), to "npm run updatedb", so that we can keep on using the database update script provided by geoip-country (which is super handy).

New GeoIP download URL is the following: `https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&suffix=zip&license_key={LICENSE_KEY}`

Notice: sadly, they seem to distribute the CSV edition of the database only in a Zip archive now. No tar.gz suffix available for this one.

I can submit a PR, just let me know before I start working on it if that's OK for you.

**Comment by sapics** [comment]
Thanks @valeriansaliou for your suggestions!
Of course "OK" :)
This feature would help us a lot!

**Comment by valeriansaliou** [comment]
Cool, I'll be working on it through the afternoon and submit a PR. ;)

**Comment by valeriansaliou** [comment]
Opened PR #4

**Comment by sapics** [comment]
Thanks @valeriansaliou, quick work and beautiful code!!
Now, I publish v3.4.0 in npm.

**Comment by valeriansaliou** [comment]
Thanks, that was fast! Perfect :)
