### ISSUE TITLE
Error: Cannot find module '../../node_modules/countries-list/countries.min.json'

### ISSUE THREAD

**Issue by ajithv11** [sapics/geoip-country#31]
Could you please update the file node_modules/geoip-country/lib/geoip.js as follows

`
var countryJson = require('../../countries-list/countries.min.json');
var continentJson = require('../../countries-list/continents.min.json');

`

**Comment by sapics** [comment]
Thank you for reporting error!
I have fixed the issue and release a newer version.

**Comment by sapics** [comment]
I close this issue as fixed.

**Comment by satyam7world** [comment]
actually it is completly opposite  in bun runtime after  fixing the error the bun runtime  is giving this same error, i am using old version to solve the issue .
i am using elysia js
