### ISSUE TITLE
Download Not Allowed

### ISSUE THREAD

**Issue by RoelRoel** [sapics/geoip-country#5]
I allways get "Retrieving GeoLite2-Country-CSV.zip ...ERROR: Download Not Allowed — Is Your License Key Valid? [HTTP 401]"

I followed all the instuctions and requested a licence key at maxmind.

I try to update the data via a script in my package.json with the following content:
set npm_config_license_key=...my key... && node node_modules/geoip-country/scripts/updatedb.js

**Comment by sapics** [comment]
I update to v3.4.1.
In this version, you can use environment variable `GEOLITE2_LICENSE_KEY`. It would help you!

**Comment by RoelRoel** [comment]
It does not help. I still get
ERROR: Download Not Allowed — Is Your License Key Valid? [HTTP 401]

Do I need the advanced way to get a licence key at Maxmind? What are the settings?

**Comment by sapics** [comment]
When I test, it works without any trouble in Windows10.
Which OS do you use? And how about this command?
```console
cd node_modules/geoip-country && npm run-script updatedb --license_key=YOUR_GEOLITE2_LICENSE_KEY
```

**Comment by sapics** [comment]
Now, I create a new version 4.0.
I change the major version, because the LICENSE and EULA are changed.

`geoip-country` updates weekly from MaxMind database.
Thus, just updating `geoip-country` in npm would be enough :)

**Comment by AtAFork** [comment]
Works for me on Ubuntu 18, thanks @sapics for updating since MaxMInd recently introduced breaking changes.

**Comment by sapics** [comment]
Thanks @AtAFork for reporting!

**Comment by sapics** [comment]
I close this issue.
It will be reopened, if any trouble information is provided.
